name: Deploy SQL Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy SQL Scripts
      env:
        SERVER: ${{ secrets.SQL_SERVER }}
        DATABASE: ${{ secrets.SQL_DATABASE }}
        USER: ${{ secrets.SQL_USER }}
        PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        pwsh -File ./scripts/deploy-sql-scripts.ps1 -Server $env:SERVER -Database $env:DATABASE -User $env:USER -Password $env:PASSWORD
