name: Deploy SQL Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy SQL Scripts
      env:
        SERVER: ${{ secrets.SQL_SERVER }}
        DATABASE: ${{ secrets.SQL_DATABASE }}
        USER: ${{ secrets.SQL_USER }}
        PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        $sqlScriptDirectory = 'database/StoredProcedure/'
        $connectionString = "Server=$env:SERVER;Database=$env:DATABASE;User Id=$env:USER;Password=$env:PASSWORD;"
        
        $connection = New-Object System.Data.SqlClient.SqlConnection
        $connection.ConnectionString = $connectionString
        $connection.Open()

        # Get all SQL script files from the directory
        $sqlScriptFiles = Get-ChildItem -Path $sqlScriptDirectory -Filter *.sql

        foreach ($file in $sqlScriptFiles) {
            Write-Host "Executing script: $($file.FullName)"
            $sqlScript = Get-Content -Path $file.FullName -Raw
            
            $command = $connection.CreateCommand()
            $command.CommandText = $sqlScript
            $command.ExecuteNonQuery()
        }

        $connection.Close()

        Write-Host "All SQL scripts executed successfully."
