name: Find File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  find-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Find GetEmployees.sql
      run: |
        echo "Searching for GetEmployees.sql in the repository..."
        find . -name "GetEmployees.sql" || echo "File not found"
