name: Deploy SQL Scripts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Working Directory
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -R

      - name: List Contents of the Target Directory
        run: |
          echo "Listing target directory:"
          cd dbScript/database/StoredProcedure
          ls -R

      - name: Execute PowerShell Script
        run: |
          cd dbScript/database/StoredProcedure
          pwsh -File export-script.ps1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sql-scripts
          path: dbScript/database/StoredProcedure/
